baseURL = "http://sanghoho.github.io"
title = "R is Well"

languageCode = "ko-KR"
DefaultContentLanguage = "en"
theme = "hello-programmer"
disqusShortname = "XXXX"
googleAnalytics = "UA-XXXXXXXX-X"
paginate = 5
pygmentsCodeFences = true # Code Highlighting
# pygmentsStyle = "friendly"

publishdir = "public"

summaryLength = 30

[taxonomies]
  category = "categories"
  subcategory = "subcategories"
  tag = "tags"

[permalinks]
    post = "/post/:filename/"
    fixed = "/:filename"

[author]
    name = "Sangho Ahn"
    email = "ash1151@ajou.ac.kr"

[params]
    description = "My Blog about Business, Coding, Data-Analysis and Math"
    katex = true
